import * as React from 'react';
import Button from '@mui/material/Button';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import { /*FaRegCopy, FaShareAlt, */ FaEllipsisV } from 'react-icons/fa';
import { getUspTrade, getSecurityDetail, getPriceHistory, getShowLoans, getAccountDetails } from '../api';
import { dateFormatter, dateSorterMMDDYYY, dollarFormatter, dollarFormatter0, formatWeight, numberFormatter2, omitNullColumns, sqlDateToDateString } from '../utils/helperFunctions';
import CustomCell from './CustomCell';

export default function CustomMaterialMenu({ row, handleModalOption1Open, handleModalOption2Open, handleModalOption3Open, handleModalOption4Open, handleModalOption5Open}) {
    const [anchorEl, setAnchorEl] = React.useState(null);
    const open = Boolean(anchorEl);
    //const [openModal, setOpenModal] = React.useState(false);
    //const [option1Data, setOption1Data] = React.useState(null)


    const handleClick = (event) => {
        console.log("Row from Options: ", row);
        //console.log("Current Target: ", event.currentTarget);
        setAnchorEl(event.currentTarget);
    };
    const handleClose = () => {
        setAnchorEl(null);
    };
    const handleModalClickRecentTrade = async (event) => {
        const uspTradeRes = await getUspTrade({ account: row.account, cusip: row.bbg_cusip});
        const title = 'Recent Trade History';
        const recentTradeModalColumns = [
            {
                name: "Trade Date",
                selector: (row) => sqlDateToDateString(dateFormatter(row.trade_date)),
                compact: true,
                reorder: true,
            },
            {
                name: "Settle Date",
                selector: (row) => sqlDateToDateString(dateFormatter(row.settle_date)),
                compact: true,
                reorder: true,
            },
            {
                name: "Transaction Type",
                selector: (row) => row.trans_type,
                compact: true,
                reorder: true,
            }, 
            {
                name: "Account",
                selector: (row) => row.account,
                compact: true,
                reorder: true,
                minWidth: "60px",
                wrap: true,
            }, 
            {
                name: "Advent Portfolio ID",
                selector: (row) => row.advPortfolioId,
                compact: true,
                reorder: true,
                minWidth: "120px",
            },
            {
                name: "Advent Security ID",
                selector: (row) => row.advSecurityId,
                compact: true,
                reorder: true,
                minWidth: "120px",
            },
            {
                name: "Security Name",
                selector: (row) => row.sec_name,
                compact: true,
                reorder: true,
                minWidth: "86px",
                wrap: true,
            },
            {
                name: "Pool Name",
                selector: (row) => row.pool_name,
                compact: true,
                reorder: true,
                minWidth: "86px",
                wrap: true, 
            },
            {
                name: "CUSIP",
                selector: (row) => row.cusip,
                compact: true,
                reorder: true,
                minWidth: "90px",
            },
            {
                name: "Symbol",
                selector: (row) => row.symbol,
                compact: true,
                reorder: true,
            },
            {
                name: "Original Face",
                selector: (row) => dollarFormatter0.format(row.orig_face),
                compact: true,
                reorder: true,
            },
            {
                name: "Current Face",
                selector: (row) => dollarFormatter0.format(row.curr_face),
                compact: true,
                reorder: true,
            },
            {
                name: "Price",
                selector: (row) => dollarFormatter.format(row.price),
                compact: true,
                reorder: true,
                minWidth: "75px",
            },
            {
                name: "Accrued",
                selector: (row) => dollarFormatter.format(row.accrued),
                compact: true,
                reorder: true,
                minWidth: "80px",
            },
            {
                name: "Net Money",
                selector: (row) => dollarFormatter.format(row.net_money),
                compact: true,
                reorder: true,
            },
            {
                name: "Dealer",
                selector: (row) => row.dealer,
                compact: true,
                reorder: true,
                wrap: true,
            },
        ];

        if (uspTradeRes.length === 0) {
            alert(`No recent trade has been located for this CUSIP.`);
        } else {
            //Insert modal here!
            //setOpenModal(true);
            handleModalOption1Open(uspTradeRes, title, recentTradeModalColumns);
        }
    };
    const handleModalClickSecurityDetail = async(event) => {       
        const securityDetailRes = await getSecurityDetail({ cusip: row.bbg_cusip});
        const title = 'Security Detail';
        const securityDetailModalColumns = [
            {
                name: 'ID',
                selector: (row) => row.id,
                compact: true,
                reorder: true,
                minWidth: '60px',
            },
            {
                name: 'CUSIP',
                selector: (row) => row.cusip,
                compact: true,
                reorder: true,
                minWidth: '80px'
            }, 
            {
                name: 'Ticker',
                selector: (row) => row.ticker,
                compact: true,
                reorder: true
            },
            {
                name: 'Name',
                selector: (row) => row.name,
                compact: true,
                reorder: true,
                maxWidth: '150px',
                wrap: true,
            },
            {
                name: 'LT Date',
                selector: (row) => sqlDateToDateString(dateFormatter(row.lastTradeableDate)),
                compact: true,
                reorder: true,
            },
            {
                name: 'Last Price',
                selector: (row) => dollarFormatter.format(row.lastPrice),
                compact: true,
                reorder: true,
            },
            {
                name: 'Issuer',
                selector: (row) => row.issuer,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: 'Sec Type',
                selector: (row) => row.security_typ,
                compact: true,
                reorder: true,
            },
            {
                name: 'GICS Industry Group',
                selector: (row) => row.gics_industry_group,
                compact: true,
                reorder: true,
                minWidth: '150px'
            },
            {
                name: 'GICS Sec',
                selector: (row) => row.gics_sector,
                compact: true,
                reorder: true,
            },
            {
                name: 'BICS 2 Ind Group Name',
                selector: (row) => row.bics_level_2_industry_group_name,
                compact: true,
                reorder: true,
                minWidth: '160px',
            },
            {
                name: 'EXCH Code',
                selector: (row) => row.exch_code,
                compact: true,
                reorder: true,
            },
            {
                name: 'Primary EXCH Name',
                selector: (row) => row.primary_exchange_name,
                compact: true,
                reorder: true,
                minWidth: '120px'
            },
            {
                name: 'Ind Group',
                selector: (row) => row.industry_group,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: 'Country',
                selector: (row) => row.country,
                compact: true,
                reorder: true,
            },
            {
                name: 'Market Sec Des',
                selector: (row) => row.market_sector_des,
                compact: true,
                reorder: true,
            },
            {
                name: '144A Flag',
                selector: (row) => row.one_four_four_a_flag,
                compact: true,
                reorder: true,
            },
            {
                name: 'Muni Issue Size',
                selector: (row) => row.muni_issue_size,
                compact: true,
                reorder: true,
            },
            {
                name: 'Mtg Agency Backed',
                selector: (row) => row.mtg_is_agency_backed,
                compact: true,
                reorder: true,
                minWidth: '110px'
            }
        ]

        if (securityDetailRes.length === 0) {
            alert(`This security has no details to display.`);
        } else {
            handleModalOption2Open(securityDetailRes, title, securityDetailModalColumns);
        }
    }
    const handleModalClickPriceHistory = async(event) => {
        //Mock data, just need to implement middle-tier endpoint and call here for 'priceHistoryRes' 
        //const priceHistoryRes = [{ aoDate: '2023-08-02', cusip: '00091XAA5', priceValue: '100.003'}];
        const priceHistoryRes = await getPriceHistory({ cusip: row.bbg_cusip });
        const title = 'Price History';
        const priceHistoryModalColumns = [
            {
                name:'AO Date',
                selector: (row) => sqlDateToDateString(dateFormatter(row.aoDate)),
                compact: true,
                reorder: true,
                sortable: true,
                sortFunction: dateSorterMMDDYYY,
            },
            {
                name: 'CUSIP',
                selector: (row) => row.cusip,
                compact: true,
                reorder: true,
            },
            {
                name: 'PriceValue',
                selector: (row) => dollarFormatter.format(row.priceValue),
                compact: true,
                reorder: true,
                sortable: true,
            }
        ];
        
        if (priceHistoryRes.length === 0) {
            alert(`This CUSIP has no Price History.`);
        } else {
            handleModalOption3Open(priceHistoryRes, title, priceHistoryModalColumns);
        }
    };
    const handleModalClickShowLoans = async(event) => {
        const showLoansRes = await getShowLoans({ cusip: row.bbg_cusip });
        const title = 'Show Loans';
        const showLoansModalColumns = [
            {   id: "cusip",
                name: 'Cusip',
                selector: (row, index) => row.cusip,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "loanId",
                name: 'Loan ID',
                selector: (row) => row.loandId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "issuer",
                name: 'Issuer',
                selector: (row) => row.issuer,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "securityName",
                name: 'Security Name',
                selector: (row,index) => row.securityName,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "rehab",
                name: 'Rehab',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.rehab === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordable",
                name: 'Affordable',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.affordable === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "artsCul",
                name: 'Arts cul',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.artsCul === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "disRec",
                name: 'Dis Rec',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.disRec === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "educ",
                name: 'Educ',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.educ === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "entDev",
                name: 'EntDev',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.entDev === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "green",
                name: 'Green',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.green === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "gender",
                name: 'Gender',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.gender === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "gov",
                name: 'Gov',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.gov === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "healthy",
                name: 'Healthy',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.healthy === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "humEmp",
                name: 'Human Empathy',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.humEmp === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "minority",
                name: 'Minority',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.minority === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "revit",
                name: 'Revit',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.revit === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "rural",
                name: 'Rural',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.rural === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "seniors",
                name: 'Seniors',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.seniors === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "agr",
                name: 'Agricultural',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.agr === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {

                id: "tod",
                name: 'TOD',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.tod === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "economic",
                name: 'Economic',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.economic === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "faith",
                name: 'Faith',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.faith === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "mCares",
                name: 'mCares',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.mCares === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "covid",
                name: 'COVID',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.covid === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "mCaresInitiative",
                name: <div>mCares Initiative</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.mCaresInitiative === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "covidInitiative",
                name: <div>COVID Initiative</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.covidInitiative === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "securityId",
                name: 'Security ID',
                selector: (row,index) => row.securityId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "number",
                name: 'Number',
                selector: (row,index) => row.number,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "rate",
                name: 'Rate',
                selector: (row,index) => formatWeight(row.rate),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "amount",
                name: 'Amount',
                selector: (row,index) => dollarFormatter0.format(row.amount),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "fico",
                name: 'FICO',
                selector: (row,index) => row.fico,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "term",
                name: 'Term',
                selector: (row,index) => row.term,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ltv",
                name: 'LTV',
                selector: (row,index) => row.ltv,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "occupancy",
                name: 'Occupancy',
                selector: (row,index) => row.occupancy,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "securityType",
                name: 'Security Type',
                selector: (row,index) => row.securityType,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "address",
                name: 'Address',
                selector: (row,index) => row.address,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "cityId",
                name: 'City ID',
                selector: (row,index) => row.cityId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "city",
                name: 'City',
                selector: (row,index) => row.city,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "stateId",
                name: 'State ID',
                selector: (row,index) => row.stateId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "state",
                name: 'State',
                selector: (row,index) => row.state,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "stateCountyCode",
                name: <div>State County Code</div>,
                selector: (row,index) => row.stateCountyCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "classCode",
                name: 'Class Code',
                selector: (row,index) => row.classCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "county",
                name: 'County',
                selector: (row,index) => row.county,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "isPPC",
                name: 'Is PPC',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.isPPC === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "zipCode",
                name: 'Zip Code',
                selector: (row,index) => row.zipCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "annualIncome",
                name: 'Annual Income',
                selector: (row,index) => dollarFormatter.format(row.annualIncome),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "msaNumber",
                name: 'MSA Number',
                selector: (row,index) => row.msaNumber,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "percentMedian",
                name: 'Percent Median',
                selector: (row,index) => row.percentMedian,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "mfiId",
                name: 'MFI ID',
                selector: (row,index) => row.mfiId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "censusTract",
                name: 'Census Tract',
                selector: (row,index) => row.censusTract,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "liRatio",
                name: 'LI Ratio',
                selector: (row,index) => row.liRatio,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ccmPercentOfMf",
                name: <div>CCM Percent Of MF</div>,
                selector: (row,index) => row.ccmPercentOfMf,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "expr1",
                name: 'Expr 1',
                selector: (row,index) => row.expr1,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "race",
                name: 'Race',
                selector: (row,index) => row.race,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "ethnicity",
                name: 'Ethnicity',
                selector: (row,index) => row.ethnicity,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "ffiecMsaCode",
                name: <div>FFIEC MSA Code</div>,
                selector: (row,index) => row.ffiecMsaCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id :"ffiecCountyCode",
                name: <div>FFIEC County Code</div>,
                selector: (row,index) => row.ffiecCountyCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecCensusTract",
                name: <div>FFIEC Census Tract</div>,
                selector: (row,index) => row.ffiecCensusTract,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecCountyName",
                name: <div>FFIEC County Name</div>,
                selector: (row,index) => row.ffiecCountyName,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecIncomeLevel",
                name: <div>FFIEC Income Level</div>,
                selector: (row,index) => row.ffiecIncomeLevel,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecDistressed",
                name: <div>FFIEC Distressed</div>,
                selector: (row,index) => row.ffiecDistressed,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecMfi",
                name: <div>FFIEC MFI</div>,
                selector: (row,index) => row.ffiecMfi,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecTractPercentMinority",
                name: <div>FFIEC Tract Percent Minority</div>,
                selector: (row,index) => row.ffiecTractPercentMinority,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecPercentPoverty",
                name: <div>FFIEC Percent Poverty</div>,
                selector: (row,index) => row.ffiecPercentPoverty,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecStateCode",
                name: <div>FFIEC State Code</div>,
                selector: (row,index) => row.ffiecStateCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecMsamfiPercent",
                name: <div>FFIEC MSA MFI Percent</div>,
                selector: (row,index) => row.ffiecMsamfiPercent,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecState",
                name: <div>FFIEC State</div>,
                selector: (row,index) => row.ffiecState,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecZipoCode",
                name: <div>FFIEC Zipo Code</div>,
                selector: (row,index) => row.ffiecZipoCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "walkScore",
                name: 'Walk Score',
                selector: (row,index) => row.walkScore,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "walkScoreDescription",
                name: <div>Walk Score Description</div>,
                selector: (row,index) => row.walkScoreDescription,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "bikeScore",
                name: 'Bike Score',
                selector: (row,index) => row.bikeScore,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "bikeScoreDescription",
                name: <div>Bike Score Description</div>,
                selector: (row,index) => row.bikeScoreDescription,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "transitScore",
                name: 'Transit Score',
                selector: (row,index) => row.transitScore,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "transitScoreDescription",
                name: <div>Transit Score Description</div>,
                selector: (row,index) => row.transitScoreDescription,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "latitude",
                name: 'Latitude',
                selector: (row,index) => numberFormatter2.format(row.latitude),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "longitude",
                name: 'Longitude',
                selector: (row,index) => numberFormatter2.format(row.longitude),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "gender2",
                name: 'Gender 2',
                selector: (row,index) => row.gender2,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "race2",
                name: 'Race 2',
                selector: (row,index) => row.race2,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ethnicity2",
                name: 'Ethnicity 2',
                selector: (row,index) => row.ethnicity2,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "poolNumber",
                name: 'Pool Number',
                selector: (row,index) => row.poolNumber,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "expr2",
                name: 'Expr 2',
                selector: (row,index) => row.expr2,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "originalAmount",
                name: 'Orig Amount',
                selector: (row,index) => row.originalAmount,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "currentFactor",
                name: 'Curr Factor',
                selector: (row,index) => row.currentFactor,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "currentAmount",
                name: 'Curr Amount',
                selector: (row,index) => row.currentAmount,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "propertyName",
                name: 'Property Name',
                selector: (row,index) => row.propertyName,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "issueDate",
                name: 'Issue Date',
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.issueDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "maturityDate",
                name: 'Maturity Date',
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.maturityDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableId",
                name: 'Affordable ID',
                selector: (row,index) => row.affordableId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "fhaCasNumber",
                name: <div>FHA Case Number</div>,
                selector: (row,index) => row.fhaCasNumber,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "acknowledgeUnaffordable",
                name: <div>Acknowledge Unaffordable</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.acknowledgeUnaffordable === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unaffordableComment",
                name: <div>Unaffordable Comment</div>,
                selector: (row,index) => row.unaffordableComment,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unaffordableOverridingUserId",
                name: <div>Unaffordable Overriding User ID</div>,
                selector: (row,index) => row.unaffordableOverridingUserId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "mfi",
                name: 'MFI',
                selector: (row,index) => row.mfi,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unitsA",
                name: 'Units A',
                selector: (row,index) => row.unitsA,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unitsB",
                name: 'Units B',
                selector: (row,index) => row.unitsB,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "nonCraQualified",
                name: <div>Non CRA Qualified</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.nonCraQualified === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "contract",
                name: 'Contract',
                selector: (row,index) => row.contract,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "contractStartDate",
                name: <div>Contract Start Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.contractStartDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "contractEndDate",
                name: <div>Contract End Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.contractEndDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "createDate",
                name: <div>Create Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.createDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecLookedUp",
                name: <div>FFIEC Looked Up</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.ffiecLookedUp === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "recapLoan",
                name: 'Recap Loan',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.recapLoan === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "trackerLoanId",
                name: <div>Tracker Loan ID</div>,
                selector: (row,index) => row.trackerLoanId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "generalText",
                name: 'General Text',
                selector: (row,index) => row.generalText,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "googleAddress",
                name: <div>Google Address</div>,
                selector: (row,index) => row.googleAddress,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "googleLookedUp",
                name: <div>Google Looked Up</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.googleLookedUp === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "difficultDevelopmentArea",
                name: <div>Difficult Development Area</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.difficultDevelopmentArea === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ruralCensusTractAndMsa",
                name: <div>Rural Census Tract and MSA</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.ruralCensusTractAndMsa === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "persistentPovertyCounty",
                name: <div>Persistent Poverty County</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.persistentPovertyCounty === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ffiecLookupDate",
                name: <div>FFIEC Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.ffiecLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "walkScoreLookupDate",
                name: <div>Walk Score Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.walkScoreLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "recapLookupDate",
                name: <div>Recap Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.recapLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "difficultDevelopmentAreaLookupDate",
                name: <div>Difficult Dev Area Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.difficultDevelopmentAreaLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "persistentPovertyCountyLookupDate",
                name: <div>Persistent Poverty County Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.persistentPovertyCountyLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "geoCodedDate",
                name: <div>Geo Coded Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.geoCodedDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "censusDataDate",
                name: <div>Census Data Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.censusDataDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "ruralCensusTractAndMsaLookupDate",
                name: <div>Rural Census Tract and MSA Lookup Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.ruralCensusTractAndMsaLookupDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unitsC",
                name: 'Units C',
                selector: (row,index) => row.unitsC,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "unitsD",
                name: 'Units D',
                selector: (row,index) => row.unitsD,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "expr3",
                name: 'Expr 3',
                selector: (row,index) => row.expr3,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "msaCode",
                name: 'MSA Code',
                selector: (row,index) => row.msaCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "msaName",
                name: 'MSA Name',
                selector: (row,index) => row.msaName,
                compact: true,
                reorder: true,
                center: true,
                wrap: true,
            },
            {
                id: "source",
                name: 'Source',
                selector: (row,index) => row.source,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "year",
                name: 'Year',
                selector: (row,index) => row.year,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "useAsCurrent",
                name: <div>Use As Current</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.useAsCurrent === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "recordType",
                name: 'Record Type',
                selector: (row,index) => row.recordType,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "propertyId",
                name: 'Property ID',
                selector: (row,index) => row.propertyId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "expr4",
                name: 'Expr 4',
                selector: (row,index) => row.expr4,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableAddress",
                name: <div>Affordable Address</div>,
                selector: (row,index) => row.affordableAddress,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableCity",
                name: 'Affordable City',
                selector: (row,index) => row.affordableCity,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableState",
                name: 'Affordable State',
                selector: (row,index) => row.affordableState,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableZip",
                name: 'Affordable Zip',
                selector: (row,index) => row.affordableZip,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableCountyCode",
                name: <div>Affordable County Code</div>,
                selector: (row,index) => row.affordableCountyCode,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "affordableCounty",
                name: <div>Affordable County</div>,
                selector: (row,index) => row.affordableCounty,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "totalUnits",
                name: 'Total Units',
                selector: (row,index) => row.totalUnits,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "tracsOverallExpirationDate",
                name: <div>Tracs Overall Expiration Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.tracsOverallExpirationDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "tracsStatusName",
                name: <div>Tracs Status Name</div>,
                selector: (row,index) => row.tracsStatusName,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "assistedUnitsCount",
                name: <div>Assisted Units Count</div>,
                selector: (row,index) => row.assistedUnitsCount,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "hudId",
                name: 'HUD ID',
                selector: (row,index) => row.hudId,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "nUnits",
                name: 'N Units',
                selector: (row,index) => row.nUnits,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "liUnits",
                name: 'LI Units',
                selector: (row,index) => row.liUnits,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "yrAlloc",
                name: <div>Year Allocation</div>,
                selector: (row,index) => row.yrAlloc,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "custom",
                name: 'Custom',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.custom === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "isLegacy",
                name: 'Is Legacy',
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.isLegacy === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "isRolledUp",
                name: <div>Is Rolled Up</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.isRolledUp === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "isDateMismatch",
                name: <div>Is Dated Mismatched</div>,
                selector: (row,index) => <input className="form-check-input" type="checkbox" value="" disabled checked={row.isDateMismatch === true ? true : false }/>,
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "tracsEffectiveDate",
                name: <div>Tracs Effective Date</div>,
                selector: (row,index) => sqlDateToDateString(dateFormatter(row.tracsEffectiveDate)),
                compact: true,
                reorder: true,
                center: true,
            },
            {
                id: "contractNumber",
                name: 'Contract Number',
                selector: (row,index) => row.contractNumber,
                compact: true,
                reorder: true,
                center: true,
            },
        ];
        if (showLoansRes.length === 0) {
            alert(`No underlying loans has been found for this CUSIP.`);
        } else {
            const showLoansEmptyColsOmitted = omitNullColumns(showLoansRes, showLoansModalColumns);
            handleModalOption4Open(showLoansRes, title, showLoansEmptyColsOmitted);
        }
    };
    const handleModalClickAccountDetails = async(event) => {
        const accountDetailsRes = await getAccountDetails({ apxPortfolioCode: row.account });
        const title = 'Account Details';
        const accountDetailsModalColumns = [
            {
                name: "ID",
                selector: (row) => row.id,
                compact: true,
                reorder: true,
            },
            {
                name: "Name",
                selector: (row) => row.name,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: "Number",
                selector: (row) => row.number,
                compact: true,
                reorder: true,
            },
            {
                name: "Ticker",
                selector: (row) => row.ticker,
                compact: true,
                reorder: true,
            },
            {
                name: "APX Portfolio Code",
                selector: (row) => row.apxPortfolioCode,
                compact: true,
                reorder: true,
                wrap: true,
                minWidth: "140px"
            },
            {
                name: "Open Date",
                selector: (row) => sqlDateToDateString(dateFormatter(row.openDate)),
                compact: true,
                reorder: true,
            },
            {
                name: "Close Date",
                selector: (row) => sqlDateToDateString(dateFormatter(row.closeDate)),
                compact: true,
                reorder: true,
            },
            {
                name: "Custodian ID",
                selector: (row) => row.custodianId,
                compact: true,
                reorder: true,
            },
            {
                name: "IMA ID",
                selector: (row) => row.imaId,
                compact: true,
                reorder: true,
            },
            {
                name: "Composite Affiliation ID",
                selector: (row) => row.compositeAffiliationId,
                compact: true,
                reorder: true,
            },
            {
                name: "Tracker ID",
                selector: (row) => row.trackerId,
                compact: true,
                reorder: true,
            },
            {
                name: "APX Portfolio ID",
                selector: (row) => row.apxPortfolioId,
                compact: true,
                reorder: true,
            },
            {
                name: "Delivery Instructions",
                selector: (row) => row.deliveryInstructions,
                minWidth: '200px',
                cell: (row) => <CustomCell cellData={row.deliveryInstructions} /> ,
                compact: true,
                reorder: true,
            },
            {
                name: "Fax Number",
                selector: (row) => row.faxNumber,
                compact: true,
                reorder: true,
            },
            {
                name: "Fax Cover To",
                selector: (row) => row.faxCoverTo,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: "Fax Phone",
                selector: (row) => row.faxPhone,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: "Fax Cover Subject",
                selector: (row) => row.faxCoverSubject,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: "Fax Cover Body",
                selector: (row) => row.faxCoverBody,
                compact: true,
                reorder: true,
                wrap: true,
            },
            {
                name: "APX Custodian",
                selector: (row) => row.apxCustodian,
                compact: true,
                reorder: true,
            },
            {
                name: "MGR Code",
                selector: (row) => row.mgrCode,
                compact: true,
                reorder: true,
            },
        ]

        if (accountDetailsRes.length === 0) {
            alert(`This account has no details to show!`);
        } else {
            handleModalOption5Open(accountDetailsRes, title, accountDetailsModalColumns);
        }
    };

    return (
    <div style={{ minWidth: "25px"}}>
        <Button style={{ minWidth: "30px"}}
            id="basic-button"
            aria-controls={open ? 'basic-menu' : undefined}
            aria-haspopup="true"
            aria-expanded={open ? 'true' : undefined}
            onClick={handleClick}
        >
            <FaEllipsisV />
        </Button>
        
        <Menu
            id="basic-menu"
            anchorEl={anchorEl}
            //keepMounted
            open={open}
            onClose={handleClose}
            MenuListProps={{
                'aria-labelledby': 'basic-button',
            }}
        >
            <MenuItem onClick={handleModalClickAccountDetails} >Account Details</MenuItem>
            <MenuItem onClick={handleModalClickRecentTrade}>Recent Trades</MenuItem>
            <MenuItem onClick={handleModalClickSecurityDetail}>Security Detail</MenuItem>
            <MenuItem onClick={handleModalClickPriceHistory}>Price History</MenuItem>
            <MenuItem onClick={handleModalClickShowLoans}>Underlying Loans</MenuItem>            
        </Menu>
    </div>
    );
}